# DO NOT REPLACE entire config for your validator with this file. Use this file as guide for important values you have to update/add in your config. You may copy specific values to your config

AutoInitialiseFromNetworkHistory = false # this should be enable only for the first start when you start the data-node from the remote Snapshot then it MUST be DISABLED
ChainID = "nebula1"
MaxMemoryPercent = 33

[SQLStore]
    RetentionPeriod = "standard"

    [SQLStore.ConnectionConfig]
        Host = "localhost"
        Port = 5432
        Username = "vega"
        Password = "vega"
        Database = "vega"

[NetworkHistory]
    FetchRetryMax = 10
    Publish = true
    RetryTimeout = "15s"
    [NetworkHistory.Initialise]
        MinimumBlockCount = 100
    [NetworkHistory.Store]
        BootstrapPeers = ["/dns/api0.neb.exchange/tcp/4001/ipfs/12D3KooWBEiFW25wWBdoDZq6KTLbDywxghaP8r4UicBsuYLfLUMj", "/dns/api0.neb.exchange/tcp/4001/ipfs/12D3KooWBEiFW25wWBdoDZq6KTLbDywxghaP8r4UicBsuYLfLUMj"]
        HistoryRetentionBlockSpan = 100000 # 100k blocks is ~ 48h
